### ISSUE TITLE
Add build Action for windows/linux

### ISSUE THREAD

**Issue by syheliel** [bbuhrow/yafu#12]
github provides github action to verify whether the repo can be built. It helps you to figure out what's the true dependencies you need to run on a new machine.

**Comment by alexhiggins732** [comment]
I would love to see a github build pipeline, or even azure. Yafu is now in a state where I can no longer build it because it has external dependencies for which the source code is no longer availabe. For example, MSieve's repository is down and the link to the site is a deadlink. Meanwhile Yafu requires it to build.

Ben, could you perhaps refactor your repository to include the external dependencies you use to build? Ideally, git hub action or not, someone should be able to clone your repository and build. Find tuning for things like x32 vs x64 or for an OS, such as linux, or windows, or mac is one thing, but having external dependencies on repositories that are no longer openly available is entirely another topic.

**Comment by tdulcet** [comment]
It likely would be very helpful for setting up GitHub Actions if you could provide the list of commands you used on Windows and Linux to successfully build everything. The GitHub Actions VMs of course do not have a GPU, so one cannot run CUDA code, but one could still build CUDA code if needed...

**Comment by bbuhrow** [comment]
Yafu is not really set up to take advantage of GPUs so trying to integrate it into the build is creating unnecessary problems for yourself.  The exceptions are msieve gpu polyselect or msieve gpu linear algebra but I would argue that if you are running large enough problems to need those things then you probably shouldn't be using yafu.

I don't know anything about github build actions and I apologize that yafu is difficult to build but that's unlikely to change for the forseeable future.   I recommend WSL2 for windows.  The linux build path is far easier, IMO, and also produces much faster executables.

**Comment by n-WN** [comment]
Because `ytools` is required, building on macOS ARM64 is not convenient
